### ISSUE TITLE
[1.19.2] Swapping blocks with leaves makes them decay over time

### ISSUE THREAD

**Issue by Hiconel** [tinytransfem/Block_Swapper#1]
When you swap a block with a leaf block, the leaves start to decay over time, because they are not marked as persistent.

This could be intented behaviour, but I would expect any blocks being placed by the block swapper to act as if they were placed by a player.

**Comment by tinytransfem** [comment]
This is very much not intended behavior, it's an oversight on my part

**Comment by tinytransfem** [comment]
almost a year later because I somehow never ended up publishing the file, but this is now fixed in version 2.0
