### ISSUE TITLE
[1.19.2] You can make seeds grow on any block

### ISSUE THREAD

**Issue by Hiconel** [tinytransfem/Block_Swapper#2]
It is possible to swap blocks with seeds, which places the seeds on top of any block. They can even grow there.

![image](https://user-images.githubusercontent.com/1748758/194758549-71376c65-8a3a-419a-b0a8-5330a08c03bb.png)

![image](https://user-images.githubusercontent.com/1748758/194758573-f06fc43e-0798-4eec-bf03-9222742c91d0.png)

**Comment by tinytransfem** [comment]
While this wasn't originally intended behavior, it feels like a useful feature for decorating purposes, so I am now deciding to keep this in

**Comment by Hiconel** [comment]
Alright, but I thought I would also suggest this:
Granted, I don't know how much work it would be, but maybe a config option that enables or disables that behaviour would be a nice way to show it is intended?

**Comment by tinytransfem** [comment]
I'll add it to the features list on CurseForge but still great idea, will add that to the 2.0 update roadmap!

**Comment by tinytransfem** [comment]
almost a year later because I somehow never ended up publishing the file, but this is now live in version 2.0
